[project]
name = "ms-events-backend"
version = "0.1.0"
description = "Backend for ms-events"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "fastapi==0.115.6",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
